name = "cloudflare-worker"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "honc-d1-database"
database_id = "local-honc-d1-database"
migrations_dir = "drizzle/migrations"

# [vars]
# MY_VAR = "my-variable"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[assets]
directory = "./src/public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "ACTIVE_USERS", class_name = "ActiveUsersSQLite" },
  { name = "ORDER_UPDATE_SERVICE", class_name = "OrderUpdateService" }
]

[[migrations]]
tag = "v2"
new_classes = ["OrderUpdateService"]
new_sqlite_classes = ["ActiveUsersSQLite"]

[[kv_namespaces]]
binding = "VISITORS"
id = "5e802c198ef74ad6bdff5caf54fef988"
preview_id = "ed11306cc5a14282b14178bb75fb688f"

[[r2_buckets]]
bucket_name = "goose-store"
binding = "GOOSE_STORE"

# [ai]
# binding = "AI"
