apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-deployment
spec:
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      annotations:  
        dapr.io/app-id: warehouse
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
      labels:
        app: warehouse-service
        app.kubernetes.io/name: warehouse-service
        app.kubernetes.io/part-of: warehouse-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: warehouse-service
        image: salaboy/warehouse-service:1.0.3-amd64
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"
        - name: PUBLIC_IP
          value: 34.171.35.244
        - name: WORKER_URL
          value: https://cloudflare-worker.nlea.workers.dev/
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse
spec:
  selector:
    app: warehouse-service
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080